language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

sudo: false

env:
  global:
    # NPM_KEY
    - secure: WAgJZ4vx/V2GiVq1WDqvVsaH59LHAAXlBKp495GpoqzqKpkzrfemc+M8rbWkr9X2iEPCmIgfrKFIT9PaWsq3sMdMigocaD/DKDQ44MwZod7xv2FNzEWfhkPUnMAEAmfJUcfAnI4w587BT9aM+HAkdEyq2b/bPIJH8/YiC3HkfXQ=

# NPM Deploy
deploy:
  provider: npm
  email: "gustavo@injoin.com.br"
  api_key: "${NPM_KEY}"
  on:
    all_branches: true
    tags: true
